baseURL = "/"
title = "GBICP"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
# Useful when translating.
enableMissingTranslationPlaceholders = true
#disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "Grace Bible Institute"
description = "Grace Bible Institute"
languageName ="English"
contentDir = "content/en"
# Weight used for sorting.
weight = 1
[languages.zh-cn]
title = "恩典圣经学院"
description = "课程讲义"
languageName ="中文"
contentDir = "content/zh-cn"
time_format_default = "2006.01.02"
time_format_blog = "2006.01.02"
weight = 2


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

[params]
copyright = "Grace Bible Institute"
privacy_policy = "https://gbicp.org"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://gbicp.org"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/GraceBibleInstitute/website"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/GraceBibleInstitute/website"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "012145635989863727449:pp_0bsi8acq"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/GraceBibleInstitute/website/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/GraceBibleInstitute/website/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/GraceBibleInstitute/website/"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://gbicp.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"

[params.course]

front = [
	"四个关键的概念","Four Keys",
	"创世纪 12-25","Genesis 12-25",
	"旧约中的弥赛亚","Messianic Prophecy",
	"救赎之道","THE WAY OF SALVATION",
	"奥格斯堡信条 I","Augsburg Confession I",
	"给万民施洗","Baptism for All Nations",
	"认信和基督教信经","Confessing The Faith And The Christian Creeds",
	"婚姻的意义","Meaning of Marriage",
	"敬拜学","Christian Worship",
	]

# "基督徒心理辅导","Christian Counseling",
# "创世纪","Genesis",
# "罗马书 1-8","ROMANS 1-8",
# "罗马书 9-16","ROMANS 9-16",
# "律法与福音","Law and Gospel",
# "诠释圣经","Interpreting The Bible",
# "路德小教理问答","LUTHER’S SMALL CATECHISM",
# "奥格斯堡信条 I","Augsburg Confession I",
# "上帝和祂的启示","GOD AND HIS REVELATION",
# "旧约中的弥赛亚","THE MESSIAH IN THE OLD TESTAMENT",
# "捍卫自己的信仰","Defending Your Faith",
# "约翰福音","The Gospel of John",
# "60 例福音讲道（上）","60 Gospel Texts Part 1",
# "救主和他所拯救的","THE SAVIOR AND THOSE HE SAVES",
# "救赎之道","THE WAY OF SALVATION",
# "敬拜学","Christian Worship",
# "使徒行传及书信","ACTS AND EPISTLES",
# "教会节期讲道","Preaching Church Year"

rss_sections = ["courses"]

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


# [[deployment.targets]]
# # An arbitrary name for this target.
# name = "GCSdeployment"
# # The Go Cloud Development Kit URL to deploy to. Examples:
# # GCS; see https://gocloud.dev/howto/blob/#gcs
#  URL = "gs://gbicp.org"

# # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# # cloudFrontDistributionID = <ID>

# # Optionally, you can include or exclude specific files.
# # See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# # If non-empty, the pattern is matched against the local path.
# # All paths are matched against in their filepath.ToSlash form.
# # If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# # If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# # As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# # and remote files that don't pass the include/exclude filters are not deleted.
# # include = "**.html" # would only include files with ".html" suffix
# # exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# # [[deployment.matchers]] configure behavior for files that match the Pattern.
# # Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true